repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: deps
    -   id: end-of-file-fixer
        exclude: deps
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: deps
-   repo: https://github.com/psf/black
    rev: "21.7b0"
    hooks:
      - id: black
        exclude: deps
        language_version: python3
